language: perl
perl:
  - "5.10"
install:
  - sh -c "cd src && make -w"
script:
  - sh -c "cd src && make -w test"
  - ./gotcloud test --update --verbose
sudo: false # See http://docs.travis-ci.com/user/migrating-from-legacy/
